### ISSUE TITLE
Optimal default parallelism

### ISSUE THREAD

**Issue by jeremyeder** [baude/image-scanner#11]
On a 2-socket Haswell, no HT...

model name  : Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
NUMA node(s):          2
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23

Single-threaded performance of the image-scanner tooling takes about 2x as long as 4 threads.
6 threads provides nearly no benefit over 4.  > 8 threads causes issues with connecting to the Docker daemon and yields no speed improvement.

Please consider the following data:

![image-scanner-threaded-perf](https://cloud.githubusercontent.com/assets/1919640/7891154/cac94df0-0618-11e5-98c5-0ef872931ffe.png)

Based on that, please:
- Set the default value to 4 parallel threads, but handle the case where the server has less than 4 CPUs, and then set the #threads == #cores.
- Set a maximum of 4 parallel threads as there's not much benefit of increase parallelism at the moment.

[image-scanner]#  docker images -a
REPOSITORY                                               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
baude/image-scanner   latest              086f7e9b312d        2 hours ago         372.6 MB
<none>                                                   <none>              fa7066d359cb        2 hours ago         372.6 MB
<none>                                                   <none>              25cf3d7dad25        2 hours ago         372.6 MB
<none>                                                   <none>              fde75e840a79        2 hours ago         372.6 MB
<none>                                                   <none>              99c36d3c7da0        2 hours ago         372.6 MB
<none>                                                   <none>              ea71b05c060a        2 hours ago         372.6 MB
<none>                                                   <none>              587797b3fa56        2 hours ago         372.5 MB
<none>                                                   <none>              07b619c22d94        2 hours ago         372.5 MB
<none>                                                   <none>              00cca89cf573        2 hours ago         372.5 MB
<none>                                                   <none>              85e49c6ec038        2 hours ago         372.5 MB
<none>                                                   <none>              f994f486d7e2        2 hours ago         263 MB
<none>                                                   <none>              f247aebb4751        4 hours ago         195.9 MB
<none>                                                   <none>              e9d1ae7ec91b        4 hours ago         165.5 MB
<none>                                                   <none>              9849f3047a42        2 weeks ago         995.9 MB
<none>                                                   <none>              9121a61faccf        2 weeks ago         995.9 MB
<none>                                                   <none>              c1e38d7c1e7a        2 weeks ago         995.9 MB
<none>                                                   <none>              e5399201a1e8        2 weeks ago         995.9 MB
<none>                                                   <none>              e483c106db91        2 weeks ago         995.9 MB
library/r7perf        latest              1ec8c28cce60        2 weeks ago         1.276 GB
r7perf                                                   latest              1ec8c28cce60        2 weeks ago         1.276 GB
<none>                                                   <none>              b9562cd56ce0        2 weeks ago         1.276 GB
<none>                                                   <none>              035409b7e181        2 weeks ago         1.276 GB
<none>                                                   <none>              60fbd2ec0659        2 weeks ago         1.276 GB
<none>                                                   <none>              a407942b6029        2 weeks ago         1.065 GB
<none>                                                   <none>              879a729d13ac        2 weeks ago         1.026 GB
<none>                                                   <none>              5d74643946dc        2 weeks ago         995.9 MB
<none>                                                   <none>              3f438630862b        2 weeks ago         995.9 MB
<none>                                                   <none>              3fc64aeee4ab        2 weeks ago         995.9 MB
registry.access.redhat.com/rhel7/rhel-tools              latest              04c647570fa0        3 weeks ago         995.9 MB
registry.access.redhat.com/rhel7                         latest              65de4a13fc7c        3 weeks ago         154.9 MB
<none>                                                   <none>              10acc31def5d        3 months ago        154.1 MB
brew/rhel7            7.0-19-GA           f79063660f49        11 months ago       143.7 MB
brew/rhel6            6.5-7               04ce3b0d47cc        12 months ago       129.8 MB

**Comment by baude** [comment]
Fixed with https://github.com/baude/image-scanner/commit/174b4101385b000edce65a2ece43f234bd8f8a43
