### ISSUE TITLE
Give some output even if image isnt RHEL

### ISSUE THREAD

**Issue by baude** [baude/image-scanner#12]
Right now, when the imagescanner runs and the images isnt RHEL, it doesn't output anything.  That's a problem when the only image being scanned isnt RHEL as it looks like the tool didn't complete.  It should output something like:

Summary:
     Image: ded7cd95e059
     Results: ded7cd95e059 is not based on RHEL

**Comment by ajcollins0** [comment]
This was fixed in the below PR:

https://github.com/baude/image-scanner/pull/13
