### ISSUE TITLE
Better exception/error handling between docker_mount and image-scanner

### ISSUE THREAD

**Issue by baude** [baude/image-scanner#4]
My drafts of code dont handle exceptions and errors very well.  This is increasingly important due to the fact that it is run inside threads.

**Comment by ajcollins0** [comment]
Throwing some ideas off the wall here, but would it be possible to have a flag that is enabled when the disk is created/ rootfs is mounted.  That way if an exception is thrown, and we see the flag is enabled, we know that we will have to call the docker_mount.cleanup() ?
