### ISSUE TITLE
quick fixes in xml_parse

### ISSUE THREAD

**Issue by ajcollins0** [baude/image-scanner#51]
sort susceptible CVE's by crit to low

change problematic image to base image

change print_summery to show the "Scanned container" or "scanned image" to give the user the ID of the scanned object.  Then show the base image and the 'containers built with same base image' 

change print_summary to use a better printing format... i.e. below 
print "Time of Scan: {0}".format(summary['scan_time'])

**Comment by baude** [comment]
Merged
