### ISSUE TITLE
allimages and images problems in xml_parse

### ISSUE THREAD

**Issue by ajcollins0** [baude/image-scanner#56]
Line 187 in xml parse I'm getting some odd errors when I use image-scanner-remot and --allimages and  --images options, I was unsure if this was going to be fixes with your xml_parse changes you wanted to apply, If this is not alleviated with your changes then I will investigate further on Monday:

Running --allimages:
File "/home/alcollin/Desktop/work/image-scanner/image_scanner_client/xml_parse.py", line 187, in _summarize_docker_object
    for containers in docker_json['docker_state'][affected_image]:
KeyError: '10acc31def5d6f249b548e01e8ffbaccfd61af0240c17315a7ad393d022c5ca2'

Note image 10acc  is not a key in docker_json['docker_state'](also is an intermediate image) 

Running --images:
File "/home/alcollin/Desktop/work/image-scanner/image_scanner_client/xml_parse.py", line 187, in _summarize_docker_object
    for containers in docker_json['docker_state'][affected_image]:
KeyError: '65de4a13fc7cf28b4376e65efa31c5c3805e18da4eb01ad0c8b8801f4a10bc16'

Note image 65de4a13fc7c is NOT an intermediate image, I believe this should have worked

**Comment by baude** [comment]
Merged
