### ISSUE TITLE
Run image-scanner-d without any configuration files

### ISSUE THREAD

**Issue by baude** [baude/image-scanner#73]
When running the image-scanner-d in a kube environment, the configuration files for the server are overhead they would prefer to not have.  Therefore, it would be better for that environment if the image-scanner-d could be run completely from the command line with switches.

For example:

docker run -ti --rm fedora-image-scanner /usr/bin/image-scanner-d --hostip 0.0.0.0

I think the way to go about this is:

1) Check if the configuration file exists (/etc/image-scanner/image-scanner.conf)
2) If not, check if command line options are provided that would be sufficient
3) If not (2), then error out.

Additionally, we may need to add switches for where the mount points occur (double check as it used to default back to /tmp) as well as where the json files should land.

**Comment by simon3z** [comment]
@baude https://github.com/baude/image-scanner/commit/c57cf1edb8f9d71c01ddbbb7938407b2bb6092c0 works for me thanks!

**Comment by baude** [comment]
Closed
